//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphQL_API.Models.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Genres = new HashSet<Genre>();
        }
    
        public int Id { get; set; }
        public int author_id { get; set; }
        public string Name { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
